<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ResumeBuilder.Domain</AssemblyName>
    <RootNamespace>ResumeBuilder.Domain</RootNamespace>
  </PropertyGroup>

</Project>
